Temporarily comment unnecessary CI steps

diff --git a/script/ci/cloudbuild-tests-pr-pg12.yaml b/script/ci/cloudbuild-tests-pr-pg12.yaml
--- a/script/ci/cloudbuild-tests-pr-pg12.yaml
+++ b/script/ci/cloudbuild-tests-pr-pg12.yaml
@@ -101,36 +101,36 @@ steps:
   timeout: 1800s
 
 # Copy tests results and logs from the container
-- name: 'docker/compose:1.22.0'
-  entrypoint: /bin/sh
-  args:
-    - -c
-    - |
-      mkdir test_logs_${BUILD_ID}
-      docker-compose -f docker-compose-pg12.yml logs --no-color > test_logs_${BUILD_ID}/docker_compose_logs
-      docker cp builder_1:/cartodb/parallel_tests_logs test_logs_${BUILD_ID}/parallel_tests_logs
-      docker cp builder_1:/cartodb/serial_tests_logs test_logs_${BUILD_ID}/serial_tests_logs || true
-      docker cp builder_1:/cartodb/tests_exit_status tests_exit_status
-      echo "Logs will be available during 1 day at gs://cartodb-ci-tmp-logs/${BUILD_ID}/"
+# - name: 'docker/compose:1.22.0'
+#   entrypoint: /bin/sh
+#   args:
+#     - -c
+#     - |
+#       mkdir test_logs_${BUILD_ID}
+#       docker-compose -f docker-compose-pg12.yml logs --no-color > test_logs_${BUILD_ID}/docker_compose_logs
+#       docker cp builder_1:/cartodb/parallel_tests_logs test_logs_${BUILD_ID}/parallel_tests_logs
+#       docker cp builder_1:/cartodb/serial_tests_logs test_logs_${BUILD_ID}/serial_tests_logs || true
+#       docker cp builder_1:/cartodb/tests_exit_status tests_exit_status
+#       echo "Logs will be available during 1 day at gs://cartodb-ci-tmp-logs/${BUILD_ID}/"
 
 # Upload logs to gcs
-- name: gcr.io/cloud-builders/gsutil
-  args: [ '-m', 'cp', '-r', 'test_logs_${BUILD_ID}', 'gs://cartodb-ci-tmp-logs/' ]
+# - name: gcr.io/cloud-builders/gsutil
+#   args: [ '-m', 'cp', '-r', 'test_logs_${BUILD_ID}', 'gs://cartodb-ci-tmp-logs/' ]
 
 # Check tests return value and exit accordingly
-- name: gcr.io/cloud-builders/docker
-  entrypoint: /bin/bash
-  args:
-    - -c
-    - |
-      if [ $(cat tests_exit_status) == "ok" ];then
-        echo "Tests succeeded, logs are at https://console.cloud.google.com/storage/browser/cartodb-ci-tmp-logs/test_logs_${BUILD_ID}"
-        exit 0
-      else
-        cat tests_exit_status
-        echo "Tests failed, logs are at https://console.cloud.google.com/storage/browser/cartodb-ci-tmp-logs/test_logs_${BUILD_ID}"
-        exit 1
-      fi
+# - name: gcr.io/cloud-builders/docker
+#   entrypoint: /bin/bash
+#   args:
+#     - -c
+#     - |
+#       if [ $(cat tests_exit_status) == "ok" ];then
+#         echo "Tests succeeded, logs are at https://console.cloud.google.com/storage/browser/cartodb-ci-tmp-logs/test_logs_${BUILD_ID}"
+#         exit 0
+#       else
+#         cat tests_exit_status
+#         echo "Tests failed, logs are at https://console.cloud.google.com/storage/browser/cartodb-ci-tmp-logs/test_logs_${BUILD_ID}"
+#         exit 1
+#       fi
 
 
 substitutions:
